# Generated by Django 2.1.7 on 2019-06-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190527_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandagulutype',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
